import React from 'react';
import { Column } from "../../../../../models/grid.model";
import { dateFilters, textFilters } from "../../../../../utils/grid/filters";

export const getDrugDetailsColumn: () => Column<any>[] = () => {
    return [
      {
        id:1,
        position: 1,
        sorter: {},
        textCase: "upper",
        pixelWidth: 230,
        key: "labelName",
        displayTitle: "Label Name",
        isFilterable: true,
        dataType: "string",
        filters: textFilters,
        hidden: false,
        sortDirections: []
      },
      {
        id:2,
        position: 2,
        sorter: {},
        textCase: "upper",
        pixelWidth: 125,
        key: "tier",
        isFilterable: true,
        showToolTip: false,
        displayTitle: "tier",
        dataType: "string",
        filters: dateFilters,
        hidden: false,
        sortDirections: []
      },
      {
        id:3,
        position: 3,
        sorter: {},
        textCase: "upper",
        isFilterable: true,
        pixelWidth: 155,
        key: "fileType",
        displayTitle: "file type",
        dataType: "string",
        filters: dateFilters,
        hidden: false,
        sortDirections: [],
        showToolTip: false,
      },
      {
        id:4,
        position: 4,
        textCase: "upper",
        pixelWidth: 180,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "dataSource",
        displayTitle: "data source",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:5,
        position: 5,
        textCase: "upper",
        pixelWidth: 125,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "ndc",
        displayTitle: "ndc",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:6,
        position: 6,
        textCase: "upper",
        pixelWidth: 125,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "ddid",
        displayTitle: "ddid",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:7,
        position: 7,
        textCase: "upper",
        pixelWidth: 135,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "rxcui",
        displayTitle: "rxcui",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:8,
        position: 8,
        textCase: "upper",
        pixelWidth: 125,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "tty",
        displayTitle: "tty",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:9,
        position: 9,
        textCase: "upper",
        pixelWidth: 160,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "gpi",
        displayTitle: "gpi",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:10,
        position: 10,
        textCase: "upper",
        pixelWidth: 170,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "trademark",
        displayTitle: "trademark",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:11,
        position: 11,
        textCase: "upper",
        pixelWidth: 220,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "databaseCategory",
        displayTitle: "database category",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:12,
        position: 12,
        textCase: "upper",
        pixelWidth: 280,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "databaseClass",
        displayTitle: "database class",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:13,
        position: 13,
        textCase: "upper",
        pixelWidth: 170,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "createdBy",
        displayTitle: "created by",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:14,
        position: 14,
        textCase: "upper",
        pixelWidth: 205,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "createdOn",
        displayTitle: "created on",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:15,
        position: 15,
        textCase: "upper",
        pixelWidth: 170,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "modifiedBy",
        displayTitle: "modified by",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:16,
        position: 16,
        textCase: "upper",
        pixelWidth: 205,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "modifiedOn",
        displayTitle: "modified on",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:17,
        position: 17,
        textCase: "upper",
        pixelWidth: 235,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "paGroupDescription",
        displayTitle: "pa group description",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:18,
        position: 18,
        textCase: "upper",
        pixelWidth: 235,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "stGroupDescription",
        displayTitle: "st group description",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:19,
        position: 19,
        textCase: "upper",
        pixelWidth: 235,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "stepTherapyType",
        displayTitle: "step therapy type",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:20,
        position: 20,
        textCase: "upper",
        pixelWidth: 215,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "stepTherapyValue",
        displayTitle: "step therapy value",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:21,
        position: 21,
        textCase: "upper",
        pixelWidth: 225,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "qlType",
        displayTitle: "ql type",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:22,
        position: 22,
        textCase: "upper",
        pixelWidth: 150,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "qlAmount",
        displayTitle: "ql amount",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:23,
        position: 23,
        textCase: "upper",
        pixelWidth: 170,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "qlDays",
        displayTitle: "ql days",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:24,
        position: 24,
        textCase: "upper",
        pixelWidth: 182,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "moIndicator",
        displayTitle: "mo indicator",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:25,
        position: 25,
        textCase: "upper",
        pixelWidth: 182,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "mnIndicator",
        displayTitle: "mn indicator",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:26,
        position: 26,
        textCase: "upper",
        pixelWidth: 240,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "seniorSavingsModel",
        displayTitle: "senior savings model",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:27,
        position: 27,
        textCase: "upper",
        pixelWidth: 265,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "indicatedBaseFormulary",
        displayTitle: "indicated base formulary",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:28,
        position: 28,
        textCase: "upper",
        pixelWidth: 155,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "meshCui",
        displayTitle: "mesh cui",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
      {
        id:29,
        position: 29,
        textCase: "upper",
        pixelWidth: 236,
        sorter: {},
        isFilterable: true,
        showToolTip: false,
        key: "partialGapCoverage",
        displayTitle: "partial gap coverage",
        filters: textFilters,
        dataType: "string",
        hidden: false,
        sortDirections: [],
      },
    ];
  };