export const entityOwnershipData = () => {
  // return {
  //   owner: {name: "Your Own PBM"},
  //   client: {name: "Medicare"},
  //   carrier: {name: "Medicare S1234"},
  //   account: {accountno: "1234"},
  //   groups: [
  //     {
  //       id: 123,
  //       list: [
  //         "Free First Fill",
  //         "Home Infusion",
  //         "Additional Demonstratal Drugs(MMP Only)",
  //         "Value-Based Insurance",
  //         "Full Gap Coverage",
  //         "OTC Benefits",
  //         "Indicated-Base Coverage",
  //         "Senior Savings Model",
  //         "Partial Gap Coverage",
  //         "Excluded Drugs",
  //         "LIS Cost Sharing Reduction",
  //         "Other 1",
  //         "Other 2",
  //         "Other 3",
  //         "Other 4",
  //         "Other 5",
  //       ],
  //     },
  //     {
  //       id: 123,
  //       list: [
  //         "Free First Fill",
  //         "Home Infusion",
  //         "Additional Demonstratal Drugs(MMP Only)",
  //         "Value-Based Insurance",
  //         "Full Gap Coverage",
  //         "OTC Benefits",
  //         "Indicated-Base Coverage",
  //         "Senior Savings Model",
  //         "Partial Gap Coverage",
  //         "Excluded Drugs",
  //         "LIS Cost Sharing Reduction",
  //         "Other 1",
  //         "Other 2",
  //         "Other 3",
  //         "Other 4",
  //         "Other 5",
  //       ],
  //     },
  //     {
  //       id: 112,
  //       list: [
  //         "Free First Fill",
  //         "Home Infusion",
  //         "Additional Demonstratal Drugs(MMP Only)",
  //         "Value-Based Insurance",
  //         "Full Gap Coverage",
  //         "OTC Benefits",
  //         "Indicated-Base Coverage",
  //         "Senior Savings Model",
  //         "Partial Gap Coverage",
  //         "Excluded Drugs",
  //         "LIS Cost Sharing Reduction",
  //         "Other 1",
  //         "Other 2",
  //         "Other 3",
  //         "Other 4",
  //         "Other 5",
  //       ],
  //     },
  //   ],
  // };

  return {
    customer: {
      owner: "Your Own PBM",
      client: "Medicare",
      carrier: "Medicare S1234",
      account: "1234",
      groups: [
        {
          id: 123,
          list: [
            "Free First Fill",
            "Home Infusion",
            "Additional Demonstratal Drugs(MMP Only)",
            "Value-Based Insurance",
            "Full Gap Coverage",
            "OTC Benefits",
            "Indicated-Base Coverage",
            "Senior Savings Model",
            "Partial Gap Coverage",
            "Excluded Drugs",
            "LIS Cost Sharing Reduction",
            "Other 1",
            "Other 2",
            "Other 3",
            "Other 4",
            "Other 5",
          ],
        },
        {
          id: 123,
          list: [
            "Free First Fill",
            "Home Infusion",
            "Additional Demonstratal Drugs(MMP Only)",
            "Value-Based Insurance",
            "Full Gap Coverage",
            "OTC Benefits",
            "Indicated-Base Coverage",
            "Senior Savings Model",
            "Partial Gap Coverage",
            "Excluded Drugs",
            "LIS Cost Sharing Reduction",
            "Other 1",
            "Other 2",
            "Other 3",
            "Other 4",
            "Other 5",
          ],
        },
        {
          id: 112,
          list: [
            "Free First Fill",
            "Home Infusion",
            "Additional Demonstratal Drugs(MMP Only)",
            "Value-Based Insurance",
            "Full Gap Coverage",
            "OTC Benefits",
            "Indicated-Base Coverage",
            "Senior Savings Model",
            "Partial Gap Coverage",
            "Excluded Drugs",
            "LIS Cost Sharing Reduction",
            "Other 1",
            "Other 2",
            "Other 3",
            "Other 4",
            "Other 5",
          ],
        },
      ],
    },
  };
};

export const entityOwnershipData1 = () => {
  return {
    owner: {name: "Your Own PBM"},
    client: {name: "Medicare"},
    carrier: {name: "Medicare S1234"},
    account: {accountno: "1234"},
    groups: [
      {
        id: 123,
        list: [
          "Free First Fill",
          "Home Infusion",
          "Additional Demonstratal Drugs(MMP Only)",
          "Value-Based Insurance",
          "Full Gap Coverage",
          "OTC Benefits",
          "Indicated-Base Coverage",
          "Senior Savings Model",
          "Partial Gap Coverage",
          "Excluded Drugs",
          "LIS Cost Sharing Reduction",
          "Other 1",
          "Other 2",
          "Other 3",
          "Other 4",
          "Other 5",
        ],
      },
      {
        id: 123,
        list: [
          "Free First Fill",
          "Home Infusion",
          "Additional Demonstratal Drugs(MMP Only)",
          "Value-Based Insurance",
          "Full Gap Coverage",
          "OTC Benefits",
          "Indicated-Base Coverage",
          "Senior Savings Model",
          "Partial Gap Coverage",
          "Excluded Drugs",
          "LIS Cost Sharing Reduction",
          "Other 1",
          "Other 2",
          "Other 3",
          "Other 4",
          "Other 5",
        ],
      },
      {
        id: 112,
        list: [
          "Free First Fill",
          "Home Infusion",
          "Additional Demonstratal Drugs(MMP Only)",
          "Value-Based Insurance",
          "Full Gap Coverage",
          "OTC Benefits",
          "Indicated-Base Coverage",
          "Senior Savings Model",
          "Partial Gap Coverage",
          "Excluded Drugs",
          "LIS Cost Sharing Reduction",
          "Other 1",
          "Other 2",
          "Other 3",
          "Other 4",
          "Other 5",
        ],
      },
    ],
  };
};
